language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget http://apache.opensourcemirror.com/activemq/activemq-apollo/1.5/apache-apollo-1.5-unix-distro.tar.gz
  - tar xzf apache-apollo-1.5-unix-distro.tar.gz
  - sh -c "cd apache-apollo-1.5 && ./bin/apollo create apollo"
  - composer install

script:
  - phpunit --coverage-text
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server start
  - cp examples/config/rabbitmq.php tests/React/FunctionnalTests/config.php
  - phpunit -c phpunit-functionnal.xml.dist
  - rm tests/React/FunctionnalTests/config.php
  - sudo service rabbitmq-server stop
  - ./apache-apollo-1.5/apollo/bin/apollo-broker-service start
  - sleep 6
  - cp examples/config/apollo.php tests/React/FunctionnalTests/config.php
  - phpunit -c phpunit-functionnal.xml.dist
  - rm tests/React/FunctionnalTests/config.php
  - ./apache-apollo-1.5/apollo/bin/apollo-broker-service stop


