language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget http://apache.opensourcemirror.com/activemq/activemq-apollo/1.5/apache-apollo-1.5-unix-distro.tar.gz
  - tar xzf apache-apollo-1.5-unix-distro.tar.gz
  - sh -c "cd apache-apollo-1.5 && ./bin/apollo create apollo"
  - composer install

script:
  - phpunit --coverage-text
  - ./tests/React/FunctionalTests/run-functional.php rabbitmq
  - ./tests/React/FunctionalTests/run-functional.php apollo


